services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: my-aop-local-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8070:8080"